# nvblox debug config for fast testing
n_envs: 1
n_steps: 32
batch_size: 32
total_timesteps: 200
checkpoint_freq: 100
eval_freq: 100
n_eval_episodes: 1
log_dir: data/debug-logs
benchmark: true
reconstruction_policy: nvblox
