# Lightweight config for generation of sharp demo images
# Only specify values you want to override; defaults in train_config.py apply
n_envs: 1
n_steps: 2
n_epochs: 0
batch_size: 2
total_timesteps: 1
eval_freq: 2
n_eval_episodes: 1
log_dir: data/demo-logs

camera_height: 480
camera_width: 480
render_height: 480
render_width: 480