reconstruction_policy: nvblox
reconstruction_metric: voxelwise_tsdf_error

observations:
#  - camera_pose
  - camera_pose_history
  - mesh_render
  - birdview_image  # simulation RGB from birdview (concat with mesh_render)
  - weight_grid
