reconstruction_policy: open3d
reconstruction_metric: chamfer_distance

observations:
#  - camera_pose
  - camera_pose_history
  - mesh_render
  - birdview_image  # simulation RGB from birdview (concat with mesh_render)
